### ISSUE TITLE
python test.py I got an error : OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by beautifulzzzz** [google/python-dimond#1]
Hello:

I use `python test.py` and get an error:

python-dimond (master) ✗ sudo python test.py
[sudo] password for btfz: 
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    network.connect()
  File "/home/btfz/Downloads/BLE_PAPER/python-dimond/dimond/__init__.py", line 113, in connect
    self.device = btle.Peripheral(self.mac, addrType=btle.ADDR_TYPE_PUBLIC)
  File "/usr/local/lib/python2.7/dist-packages/bluepy-1.3.0-py2.7.egg/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python2.7/dist-packages/bluepy-1.3.0-py2.7.egg/bluepy/btle.py", line 426, in _connect
    self._startHelper(iface)
  File "/usr/local/lib/python2.7/dist-packages/bluepy-1.3.0-py2.7.egg/bluepy/btle.py", line 284, in _startHelper
    preexec_fn = preexec_function)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by mjg59** [comment]
Sorry for the late response - this suggests that your bluepy install is broken somehow, it's missing the Bluetooth helper.
